// altera_asmi_parallel_epcq_epcq.v

// Generated using ACDS version 21.4 67

`timescale 1 ps / 1 ps
module altera_asmi_parallel_epcq_epcq (
		input  wire        clkin,          //          clkin.clk
		input  wire        fast_read,      //      fast_read.fast_read
		input  wire        rden,           //           rden.rden
		input  wire [31:0] addr,           //           addr.addr
		input  wire        read_status,    //    read_status.read_status
		input  wire        write,          //          write.write
		input  wire [7:0]  datain,         //         datain.datain
		input  wire        shift_bytes,    //    shift_bytes.shift_bytes
		input  wire        sector_protect, // sector_protect.sector_protect
		input  wire        sector_erase,   //   sector_erase.sector_erase
		input  wire        wren,           //           wren.wren
		input  wire        read_rdid,      //      read_rdid.read_rdid
		input  wire        en4b_addr,      //      en4b_addr.en4b_addr
		input  wire        reset,          //          reset.reset
		input  wire        read_dummyclk,  //  read_dummyclk.read_dummyclk
		input  wire [2:0]  sce,            //            sce.sce
		output wire [7:0]  dataout,        //        dataout.dataout
		output wire        busy,           //           busy.busy
		output wire        data_valid,     //     data_valid.data_valid
		output wire [7:0]  status_out,     //     status_out.status_out
		output wire        illegal_write,  //  illegal_write.illegal_write
		output wire        illegal_erase,  //  illegal_erase.illegal_erase
		output wire [7:0]  rdid_out        //       rdid_out.rdid_out
	);

	epcq_altera_asmi_parallel_1910_rmd4qmi altera_asmi_parallel_epcq_epcq (
		.clkin          (clkin),          //   input,   width = 1,          clkin.clk
		.fast_read      (fast_read),      //   input,   width = 1,      fast_read.fast_read
		.rden           (rden),           //   input,   width = 1,           rden.rden
		.addr           (addr),           //   input,  width = 32,           addr.addr
		.read_status    (read_status),    //   input,   width = 1,    read_status.read_status
		.write          (write),          //   input,   width = 1,          write.write
		.datain         (datain),         //   input,   width = 8,         datain.datain
		.shift_bytes    (shift_bytes),    //   input,   width = 1,    shift_bytes.shift_bytes
		.sector_protect (sector_protect), //   input,   width = 1, sector_protect.sector_protect
		.sector_erase   (sector_erase),   //   input,   width = 1,   sector_erase.sector_erase
		.wren           (wren),           //   input,   width = 1,           wren.wren
		.read_rdid      (read_rdid),      //   input,   width = 1,      read_rdid.read_rdid
		.en4b_addr      (en4b_addr),      //   input,   width = 1,      en4b_addr.en4b_addr
		.reset          (reset),          //   input,   width = 1,          reset.reset
		.read_dummyclk  (read_dummyclk),  //   input,   width = 1,  read_dummyclk.read_dummyclk
		.sce            (sce),            //   input,   width = 3,            sce.sce
		.dataout        (dataout),        //  output,   width = 8,        dataout.dataout
		.busy           (busy),           //  output,   width = 1,           busy.busy
		.data_valid     (data_valid),     //  output,   width = 1,     data_valid.data_valid
		.status_out     (status_out),     //  output,   width = 8,     status_out.status_out
		.illegal_write  (illegal_write),  //  output,   width = 1,  illegal_write.illegal_write
		.illegal_erase  (illegal_erase),  //  output,   width = 1,  illegal_erase.illegal_erase
		.rdid_out       (rdid_out)        //  output,   width = 8,       rdid_out.rdid_out
	);

endmodule
