# LCVEX RTL 源文件列表，路径相对仓库根目录，顺序即编译顺序。
rtl/lcvex_pkg.sv
rtl/lcvex_fp_state.sv
rtl/lcvex_fp_scalar.sv
rtl/lcvex_neon_fp.sv
rtl/lcvex_neon_int.sv
rtl/lcvex_regfile.sv
rtl/lcvex_alu.sv
rtl/lcvex_muldiv.sv
rtl/lcvex_mem.sv
rtl/lcvex_mem_ram.sv
rtl/lcvex_mem_delay.sv
rtl/lcvex_mem_arb.sv
rtl/lcvex_l1_d.sv
rtl/lcvex_l1_i.sv
rtl/lcvex_l2.sv
rtl/lcvex_decode.sv
rtl/lcvex_mmu.sv
rtl/lcvex_core.sv

# B1-AXI4 / B2-EMIF / B3-L2-WB / B4-L1-Coherence / B5-SoC (FPGA 线).
rtl/lcvex_axi4_pkg.sv
rtl/lcvex_axi4_avalon_pkg.sv
rtl/lcvex_async_fifo.sv
rtl/lcvex_calibration_gate.sv
rtl/lcvex_axi4_master.sv
rtl/lcvex_axi4_avalon_adapter.sv
rtl/lcvex_cache_data_ram.sv
rtl/lcvex_l1_d_wb.sv
rtl/lcvex_l2_wb.sv
rtl/lcvex_l2_probe.sv
rtl/lcvex_cluster_pkg.sv
rtl/lcvex_l1_coherence.sv
rtl/lcvex_catapult_soc_pkg.sv
rtl/lcvex_bram_boot.sv
rtl/lcvex_bram_boot_shim.sv
rtl/lcvex_catapult_soc_axi.sv
rtl/lcvex_catapult_soc_coh.sv
rtl/lcvex_catapult_soc_top.sv
rtl/lcvex_axi4_sva.sv
rtl/lcvex_mem_router.sv
rtl/lcvex_pl011.sv
rtl/lcvex_pl061.sv
rtl/lcvex_mmio_fabric.sv
rtl/lcvex_gic.sv
