// B25 BRAM initialization/boundary smoke.
//
// The image is generated by fpga/catapult_a10/boot/build.sh and loaded via
// the byte HEX path.  This test intentionally keeps the program port idle so
// it checks power-up image visibility, reset-vector bytes, the exact 64 KiB
// boundary, and the reserved top-of-BRAM stack region.

`timescale 1ns/1ps

/* verilator lint_off PROCASSINIT */
/* verilator lint_off UNUSEDSIGNAL */
/* verilator lint_off UNDRIVEN */
/* verilator lint_off WIDTHEXPAND */

module lcvex_bram_init25_tb;

  import lcvex_pkg::*;

  localparam int DEPTH_BYTES = 1 << 16;
  parameter string BOOT_HEX_FILE = "fpga/catapult_a10/boot/build/boot.hex";
  parameter string EXPECTED_IMAGE_FILE =
      "build/agents/T-20260909-001/oracle/expected_image.hex";

  logic clk = 1'b0;
  always #5 clk = ~clk;

  logic        rst_n;
  logic        req_valid;
  mem_req_t    req;
  logic        req_accept;
  logic        rsp_valid;
  mem_rsp_t    rsp;
  logic        rsp_ready;
  logic        prog_we;
  logic [63:0] prog_addr;
  logic [7:0]  prog_strb;
  logic [63:0] prog_wdata;
  logic [31:0] dbg_addr;
  logic [63:0] dbg_rdata;
  integer errors;
  logic expected_file_open;

  lcvex_bram_boot #(
      .DEPTH_BYTES(DEPTH_BYTES),
      .SRAM_BASE(64'h0),
      .BOOT_HEX_FILE(BOOT_HEX_FILE)
  ) dut (
      .clk(clk), .rst_n(rst_n),
      .req_valid(req_valid), .req(req),
      .req_accept(req_accept), .rsp_valid(rsp_valid),
      .rsp(rsp), .rsp_ready(rsp_ready),
      .prog_we(prog_we), .prog_addr(prog_addr),
      .prog_strb(prog_strb), .prog_wdata(prog_wdata),
      .dbg_addr(dbg_addr), .dbg_rdata(dbg_rdata)
  );

  task automatic check(input logic condition, input string message);
    if (!condition) begin
      $display("FAIL: %s", message);
      errors = errors + 1;
    end
  endtask

  task automatic debug_read(input logic [31:0] address,
                            output logic [63:0] value);
    begin
      @(negedge clk);
      dbg_addr = address;
      @(posedge clk);
      @(negedge clk);
      value = dbg_rdata;
    end
  endtask

  logic [7:0] expected_mem [0:DEPTH_BYTES-1];

  function automatic logic [63:0] expected_word(input int unsigned address);
    logic [63:0] value;
    begin
      value = '0;
      for (int i = 0; i < 8; i++) begin
        value[i*8 +: 8] = expected_mem[address + i];
      end
      return value;
    end
  endfunction

  task automatic check_debug_expected(
      input logic [31:0] address,
      input string message
  );
    logic [63:0] value;
    begin
      debug_read(address, value);
      check(value == expected_word(address), message);
    end
  endtask

  task automatic request_read(input logic [63:0] address,
                              input logic [7:0] strobe,
                              output mem_rsp_t response);
    mem_req_t request;
    begin
      request = '{addr: address, we: 1'b0, strb: strobe, wdata: '0,
                  maint: MAINT_NONE, bypass: 1'b0};
      @(negedge clk);
      req_valid = 1'b1;
      req = request;
      rsp_ready = 1'b1;
      #1;
      check(req_accept, "BRAM request accepted");
      @(posedge clk);
      @(negedge clk);
      check(rsp_valid, "BRAM response valid");
      response = rsp;
      req_valid = 1'b0;
      @(posedge clk);
    end
  endtask

  initial begin
    logic [63:0] value;
    mem_rsp_t response;
    integer expected_fd;

    errors = 0;
    expected_file_open = 1'b0;
    expected_fd = $fopen(EXPECTED_IMAGE_FILE, "r");
    if (expected_fd == 0) begin
      $display("FAIL: independent expected image missing path=%s",
               EXPECTED_IMAGE_FILE);
      errors = errors + 1;
    end else begin
      $fclose(expected_fd);
      // This file is generated from ELF by check_image_contract.py, never
      // from the DUT's HEX/MIF.  The runner performs the strict byte/count/
      // hash checks before compiling this TB.
      $readmemh(EXPECTED_IMAGE_FILE, expected_mem);
      expected_file_open = 1'b1;
    end
    rst_n = 1'b0;
    req_valid = 1'b0;
    req = '0;
    rsp_ready = 1'b0;
    prog_we = 1'b0;
    prog_addr = '0;
    prog_strb = '0;
    prog_wdata = '0;
    dbg_addr = '0;

    repeat (4) @(posedge clk);
    rst_n = 1'b1;
    @(posedge clk);

    check(expected_file_open, "independent ELF-derived expected image opened");

    // The reset/debug oracle comes from the independent ELF-derived image.
    // It deliberately does not freeze the link-layout-dependent LDR imm19.
    debug_read(32'h0000_0000, value);
    check(value == expected_word(32'h0000_0000),
          "reset vector matches independent expected image");
    check_debug_expected(32'h0000_0008,
                         "second reset image word matches expected image");
    check(expected_word(32'h0000_0000) != 64'd0,
          "independent reset image is not empty");

    // [0xF000,0x10000) is reserved for the stack and starts as zero-filled
    // BRAM, while the exclusive top address itself must fault.
    check_debug_expected(32'h0000_f000,
                         "reserved stack base debug word matches expected image");
    check_debug_expected(32'h0000_fff8,
                         "last in-range debug word matches expected image");
    for (int i = 16'hf000; i < DEPTH_BYTES; i++) begin
      check(expected_mem[i] == 8'h00, "reserved stack remains zero-filled");
    end
    request_read(64'h0000_fffc, 8'h0f, response);
    check(!response.fault, "last four bytes remain inside BRAM");
    request_read(64'h0000_ffff, 8'h01, response);
    check(!response.fault, "last byte remains inside BRAM");
    request_read(64'h0000_fffc, 8'hff, response);
    check(response.fault, "cross-boundary eight-byte access returns fault");
    request_read(64'h0000_ffff, 8'h03, response);
    check(response.fault, "cross-boundary two-byte access returns fault");
    request_read(64'h0001_0000, 8'h01, response);
    check(response.fault, "exclusive BRAM top returns fault");

    if (errors == 0) $display("BRAM_INIT25_TB PASS");
    else $display("BRAM_INIT25_TB FAIL errors=%0d", errors);
    $finish;
  end

endmodule
