#!/usr/bin/env python3
"""V82 非 SVE profile 机器可检查清单的生成与校验器。

数据源为本文件内的 ROWS（权威），也可以读取 docs/V82_PROFILE_MANIFEST.md
中嵌入的同一份 JSON 进行一致性校验。脚本不新增任何 RTL/指令实现。

用法：
  python3 scripts/v82_profile_check.py                       # 校验内置 ROWS
  python3 scripts/v82_profile_check.py --validate-manifest   # 校验 manifest 嵌入 JSON
  python3 scripts/v82_profile_check.py --summary             # 打印分布
  python3 scripts/v82_profile_check.py --emit-manifest docs/V82_PROFILE_MANIFEST.md
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DEFAULT_MANIFEST = REPO / "docs" / "V82_PROFILE_MANIFEST.md"

CATEGORIES = {
    "V82-BASE",
    "V82-SELECTED-EXT",
    "V82-SVE-EXCLUDED",
    "POST-V82-DEFERRED",
}

STATUSES = {
    "implemented",
    "shim",
    "udef",
    "blocked",
    "deferred",
}

REQUIRED_FIELDS = {
    "row_id", "feature", "arch_version", "encoding", "required",
    "category", "status", "rtl", "sv_tb", "cocotb", "qemu_oracle",
    "negative", "checkpoint", "notes",
}


def R(row_id, feature, arch_version, encoding, required, category, status,
      rtl, sv_tb, cocotb, qemu_oracle, negative, checkpoint, notes):
    return {
        "row_id": row_id,
        "feature": feature,
        "arch_version": arch_version,
        "encoding": encoding,
        "required": bool(required),
        "category": category,
        "status": status,
        "rtl": rtl,
        "sv_tb": sv_tb,
        "cocotb": cocotb,
        "qemu_oracle": qemu_oracle,
        "negative": negative,
        "checkpoint": checkpoint,
        "notes": notes,
    }


# ---------------------------------------------------------------------------
# 权威清单。生成 manifest 时所有字段原样写入。
# ---------------------------------------------------------------------------
ROWS = [
    # ========== V82-BASE：基础标量 / 系统 / 异常 / MMU / Cache ==========
    R("BASE-DP-001", "Base integer add/sub immediate", "ARMv8.0-A (v8.2 profile base)",
      "ADD/ADDS/SUB/SUBS/CMP/CMN (immediate, LSL#12)", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_alu.sv; rtl/lcvex_core.sv",
      "tb/sv/lcvex_core_tb.sv; tb/sv/lcvex_crc_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 -cpu max/cortex-a76 strict lockstep; Gate D 定向/随机",
      "ADD/SUB 立即数 bit23=1 (ADDG/SUBG) 为 MTE reserved -> UDEF",
      "GPR/SP 单写, NZCV on S forms; ordinary COMMIT",
      "含 32 位零扩展、XZR/SP、CMP/CMN 别名"),
    R("BASE-DP-002", "Base integer add/sub shifted register", "ARMv8.0-A",
      "ADD/ADDS/SUB/SUBS (LSL/LSR/ASR shifted-register)", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_alu.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; hard_compiler/microbench",
      "ADD/SUB shifted-register shift_type=3 is reserved -> UDEF; logical ROR is separate implemented row",
      "GPR/NZCV, ordinary COMMIT",
      "shift amount masked to data width"),
    R("BASE-DP-003", "Base integer add/sub extended register", "ARMv8.0-A",
      "ADD/SUB extended-register (UXTB/UXTH/UXTW/SXTB/SXTH/SXTW + shift)", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_alu.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; hard_ext_addsub",
      "sa>4 保留编码 -> UDEF",
      "GPR/NZCV, ordinary COMMIT",
      "非 S 形式支持 SP"),
    R("BASE-DP-004", "Base logical immediate AND/ORR/EOR/ANDS", "ARMv8.0-A",
      "AND/ANDS/ORR/EOR (bitmask immediate; TST alias)", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_alu.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; hard_compiler_isa",
      "非法 bitmask N:immr:imms -> UDEF",
      "GPR/NZCV for S forms, ordinary COMMIT",
      "位掩码按 QEMU logic_imm_decode_wmask"),
    R("BASE-DP-005", "Base logical shifted-register", "ARMv8.0-A",
      "AND/ANDS/ORR/EOR/BIC/BICS/ORN/EON (shifted-register; MVN alias)", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_alu.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; random/Gate D",
      "shift_type=3 (logical ROR) is implemented as BASE-DP-018; ADD/SUB shifted-register shift_type=3 remains reserved UDEF",
      "GPR/NZCV, ordinary COMMIT",
      "BIC/ORN/EON 为取反族；BICS 有 NZCV"),
    R("BASE-DP-006", "Move wide immediate MOVN/MOVZ/MOVK", "ARMv8.0-A",
      "MOVN/MOVZ/MOVK (X/W, hw x16)", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_alu.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; hard_p6_isa",
      "opc=01 保留 -> UDEF; 32 位 hw>1 -> UDEF",
      "GPR, ordinary COMMIT",
      "MOV 汇编别名按 opc 区分"),
    R("BASE-DP-007", "Bitfield SBFM/UBFM", "ARMv8.0-A",
      "SBFM/UBFM (ASR/LSR/LSL/SXTB/SXTH/SXTW/UBFX etc)", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_alu.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; Gate D/random/compiler",
      "保留立即数组合由 decode 按 UDEF 拒绝",
      "GPR, ordinary COMMIT",
      "32 位写零扩展"),
    R("BASE-DP-008", "Bitfield insert BFM/BFI/BFXIL/BFC", "ARMv8.0-A",
      "BFM/BFI/BFXIL/BFC (X/W)", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_alu.sv",
      "tb/sv/lcvex_core_tb.sv; tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; hard_bfm",
      "保留编码 UDEF",
      "GPR, ordinary COMMIT",
      "字段外保留旧 Rd"),
    R("BASE-DP-009", "Multiply/Divide MUL/UDIV/SDIV", "ARMv8.0-A",
      "MUL/UDIV/SDIV (X/W)", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_muldiv.sv; rtl/lcvex_alu.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; random",
      "除零结果 0; 保留编码 UDEF",
      "GPR, multi-cycle commit",
      "多周期 64/32 位"),
    R("BASE-DP-010", "Multiply high UMULH/SMULH", "ARMv8.0-A",
      "UMULH/SMULH (X only)", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_muldiv.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; hard_p6_isa",
      "W 形式/保留编码 UDEF",
      "GPR, multi-cycle commit",
      "64x64 高 64 位"),
    R("BASE-DP-011", "MADD/MSUB and long multiply-add", "ARMv8.0-A",
      "MADD/MSUB/SMADDL/SMSUBL/UMADDL/UMSUBL", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_muldiv.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; hard_madd",
      "保留编码 UDEF",
      "GPR, multi-cycle commit",
      "32 位结果截断低 32"),
    R("BASE-DP-012", "Conditional select CSEL/CSINC/CSINV/CSNEG", "ARMv8.0-A",
      "CSEL/CSINC/CSINV/CSNEG (aliases CSET/CSETM/CINC/CINV/CNEG)", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_alu.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; hard_csel",
      "保留编码 UDEF",
      "GPR/NZCV unaffected, ordinary COMMIT",
      "条件按 ID 级 NZCV 求值"),
    R("BASE-DP-013", "Variable shifts LSLV/LSRV/ASRV/RORV", "ARMv8.0-A",
      "LSLV/LSRV/ASRV/RORV (X/W)", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_alu.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; hard_varshift",
      "保留编码 UDEF",
      "GPR, ordinary COMMIT",
      "移位量按数据宽度掩码"),
    R("BASE-DP-014", "Add/sub with carry ADC/ADCS/SBC/SBCS/NGC/NGCS", "ARMv8.0-A",
      "ADC/ADCS/SBC/SBCS/NGC/NGCS (X/W)", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_alu.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; hard_adc_sbc",
      "保留编码 UDEF",
      "GPR/NZCV, ordinary COMMIT",
      "Linux syscall 返回路径使用 NGC"),
    R("BASE-DP-015", "Bit/byte manipulation REV/REV16/REV32/RBIT/CLZ/CLS", "ARMv8.0-A",
      "REV/REV16/REV32/RBIT/CLZ/CLS (X/W)", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_alu.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; Linux 动态覆盖",
      "保留编码 UDEF",
      "GPR, ordinary COMMIT",
      "P6 Linux 启动实证"),
    R("BASE-DP-016", "Conditional compare CCMP/CCMN", "ARMv8.0-A",
      "CCMP/CCMN (immediate and register)", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_alu.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; hard_p6_isa",
      "保留编码 UDEF",
      "NZCV-only update, ordinary COMMIT",
      "条件不满足写 NZCV 立即数"),
    R("BASE-DP-017", "Extract EXTR / ROR immediate", "ARMv8.0-A",
      "EXTR (32/64; ROR #imm alias)", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_alu.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; hard_p6_isa/EXTR deep tail",
      "保留编码 UDEF",
      "GPR, ordinary COMMIT",
      "Linux alternatives 使用"),
    R("BASE-DP-018", "Logical shifted-register ROR", "ARMv8.0-A base",
      "Logical shifted-register ROR (shift_type=3)", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv",
      "tb/sv/lcvex_b1_decode_tb.sv",
      "sim/cocotb/test_alu.py; sim/cocotb/test_b1_logic_ror.py",
      "QEMU 11.1.0 decodes/executes; RTL B1 implementation added",
      "ADD/SUB shifted-register shift_type=3 is reserved and stays UDEF",
      "ordinary GPR/NZCV commit",
      "B1 已实现；不把 EXTR/RORV 当作等价实现"),
    R("BASE-RSV-001", "Reserved/unsupported scalar encodings", "ARMv8.0-A base",
      "ADDG/SUBG (MTE), MOV wide opc=01, hw>1, extended sa>4, unknown SYS", True, "V82-BASE", "udef",
      "rtl/lcvex_decode.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 UDEF EC=0x00 / sysreg trap EC=0x18; hard_* negative",
      "保留/未识别编码统一 UDEF",
      "No GPR/mem effect; exception commit",
      "这是负测行，不进入完成度"),
    R("BASE-BR-001", "Branch B/BL", "ARMv8.0-A",
      "B/BL (imm26)", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; Gate D",
      "PC range/fault IABT boundary",
      "PC/next_pc, ordinary COMMIT",
      "BL 写链接寄存器"),
    R("BASE-BR-002", "Conditional branch B.cond", "ARMv8.0-A",
      "B.cond (14 condition codes; cond=1111 as unconditional)", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 trans_B_cond; hard_bcond_f",
      "cond=1111 per QEMU unconditional",
      "PC, ordinary COMMIT",
      "NZCV 来自 ID 级"),
    R("BASE-BR-003", "Compare and branch CBZ/CBNZ", "ARMv8.0-A",
      "CBZ/CBNZ (19-bit offset)", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; Gate D",
      "保留编码 UDEF",
      "PC, ordinary COMMIT",
      "X/W 形式"),
    R("BASE-BR-004", "Test and branch TBZ/TBNZ", "ARMv8.0-A",
      "TBZ/TBNZ (14-bit offset, bit index)", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; Gate D",
      "保留编码 UDEF",
      "PC, ordinary COMMIT",
      "X/W 形式"),
    R("BASE-BR-005", "Indirect branch BR/BLR/RET", "ARMv8.0-A",
      "BR/BLR/RET (Xn)", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; hard_insn_gaps",
      "目标越界 -> IABT merged",
      "PC/linker, ordinary COMMIT",
      "RET Xn; BLR 写 LR"),
    R("BASE-MEM-001", "PC-relative address ADR/ADRP", "ARMv8.0-A",
      "ADR/ADRP (immlo/immhi)", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_alu.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; Gate D",
      "保留编码 UDEF",
      "GPR, ordinary COMMIT",
      "ADRP 页基址"),
    R("BASE-MEM-002", "Load/store unsigned immediate", "ARMv8.0-A",
      "LDR/STR (B/H/W/X, unsigned imm12)", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv; rtl/lcvex_mem.sv",
      "tb/sv/lcvex_core_tb.sv; tb/sv/lcvex_mem_if_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; Gate D/random",
      "地址越界/MMU fault -> DABT",
      "mem side effects, commit",
      "支持 SP 基址"),
    R("BASE-MEM-003", "Load/store pre/post-index", "ARMv8.0-A",
      "LDR/STR pre/post (imm9, writeback)", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; hard_postpre",
      "对 XZR 无写回; SP 支持",
      "mem + GPR/SP writeback, commit",
      "P6 Linux 启动缺口修复"),
    R("BASE-MEM-004", "Load/store register offset", "ARMv8.0-A",
      "LDR/STR [Xn, Xm, lsl #s] (8/16/32/64)", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; hard_reg_offset",
      "非法 shift/option -> UDEF",
      "mem + GPR, commit",
      "数组访问常用"),
    R("BASE-MEM-005", "Unscaled load/store LDUR/STUR", "ARMv8.0-A",
      "LDUR/STUR/LDURSW/LDURSB/LDURSH/PRFUM (imm9 unscaled)", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; hard_ldur",
      "保留编码 UDEF",
      "mem, commit",
      "P6 Linux 启动缺口"),
    R("BASE-MEM-006", "Unprivileged load/store LDTR/STTR", "ARMv8.0-A",
      "LDTR/STTR (B/H/W/X, imm9)", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; hard_ldtr_sttr",
      "保留编码 UDEF",
      "mem, commit",
      "按 EL0 权限访问"),
    R("BASE-MEM-007", "Sign-extending loads LDRSB/LDRSH/LDRSW", "ARMv8.0-A",
      "LDRSB/LDRSH/LDRSW (unsigned & reg offset, W/X)", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; hard_insn_gaps",
      "保留编码 UDEF",
      "GPR + mem, commit",
      "W 形式先符号扩展 32 再零扩展"),
    R("BASE-MEM-008", "Literal load LDR (literal)", "ARMv8.0-A",
      "LDR W/X/LDRSW literal (PC-relative ±1MiB)", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; hard_ldr_literal",
      "保留编码 UDEF",
      "mem + GPR, commit",
      "PRFM literal NOP"),
    R("BASE-MEM-009", "Prefetch PRFM/PRFUM", "ARMv8.0-A",
      "PRFM/PRFUM (literal/unsigned/unscaled)", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 NOP; strict lockstep",
      "保留编码 UDEF",
      "No architectural state change, commit",
      "顺序核按 NOP"),
    R("BASE-MEM-010", "Pair load/store LDP/STP/LDPSW", "ARMv8.0-A",
      "LDP/STP (offset/pre/post, X/W; LDPSW)", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; hard_pair_ldst",
      "非对齐/fault 边界; 保留编码 UDEF",
      "双 GPR + mem, commit",
      "双/三写回"),
    R("BASE-MEM-011", "Exclusive LDXR/STXR/LDAXR/STLXR/CLREX", "ARMv8.0-A",
      "LDXR/LDAXR/STXR/STLXR/CLREX (B/H/W/X)", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; hard_exclusive",
      "monitor 语义负测 (CLREX/ERET/STR)",
      "exclusive monitor + mem + GPR, commit/checkpoint sidecar",
      "单核顺序语义"),
    R("BASE-MEM-012", "Acquire/release LDAR/STLR", "ARMv8.0-A",
      "LDAR/STLR (B/H/W/X)", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; hard_exclusive/Linux",
      "保留编码 UDEF",
      "mem, commit",
      "顺序发射核按普通访存; 非 RCpc"),
    R("BASE-SYS-001", "NOP", "ARMv8.0-A",
      "NOP (hint space)", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep",
      "其它 hint 按 BTI/未分类处理",
      "no-op commit",
      "基础"),
    R("BASE-SYS-002", "Supervisor call SVC", "ARMv8.0-A",
      "SVC #imm", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv",
      "tb/sv/lcvex_core_tb.sv; sim/difftest/test_program.py",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 EC=0x15 strict lockstep",
      "EL0/EL1 exception entry",
      "ELR/SPSR/vector, exception commit",
      "异常 ELR=pc+4"),
    R("BASE-SYS-003", "Hypervisor/secure call HVC/SMC PSCI", "ARMv8.0-A (platform conduit)",
      "HVC #imm / SMC #imm; PSCI_VERSION/FEATURES/MIGRATE_INFO_TYPE/AFFINITY_INFO/CPU_ON", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv",
      "tb/sv/lcvex_core_tb.sv; sim/difftest/test_program.py",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 virt PSCI strict lockstep; hard_psci",
      "未实现 PSCI 函数返回 NOT_SUPPORTED",
      "GPR, ordinary commit",
      "单核最小 PSCI 子集"),
    R("BASE-SYS-004", "Exception return ERET", "ARMv8.0-A",
      "ERET", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; q6/p4b",
      "EL0 执行/目标越界边界",
      "PSTATE/SP/PC restore, exception-adjacent commit",
      "恢复 PSTATE"),
    R("BASE-SYS-005", "MRS/MSR system register access", "ARMv8.0-A",
      "MRS/MSR (EL1/EL0 system register tuple)", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv; rtl/lcvex_pkg.sv",
      "tb/sv/lcvex_core_tb.sv; sim/difftest/test_program.py",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 sysreg probe / strict lockstep",
      "EL0 越权访问 EL1 regs -> UDEF EC=0x00; unknown -> EC=0x18/UDEF",
      "sysreg state, commit/checkpoint sidecar",
      "覆盖 ISA_SCOPE 列出的寄存器矩阵"),
    R("BASE-SYS-006", "MSR immediate PSTATE", "ARMv8.0-A",
      "DAIFSet/DAIFClr/SPSel/SSBS/UAO/PAN/DIT/TCO/ALLINT immediate", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; hard_p6_isa/hard_dit/hard_allint/hard_sctlr_pauth",
      "EL0/权限边界; 保留 imm 位",
      "PSTATE + SPSR, commit",
      "DAIF 写后 pending IRQ 同边界取走"),
    R("BASE-SYS-007", "Barriers ISB/DMB/DSB/SB", "ARMv8.0-A",
      "ISB/DMB/DSB/SB (ordered/scope variants)", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv",
      "tb/sv/lcvex_core_tb.sv; tb/sv/lcvex_commit_backpressure_tb.sv; tb/sv/lcvex_b3_sys_decode_tb.sv; tb/sv/lcvex_b3_atomic_barrier_tb.sv",
      "sim/cocotb/test_lcvex_core.py; sim/cocotb/test_commit_backpressure.py",
      "QEMU 11.1.0 strict lockstep; hard_barrier/selfmod",
      "保留选项 UDEF; SB CRm!=0 UDEF",
      "drain/fetch refetch, no arch data change",
      "顺序核排空语义"),
    R("BASE-SYS-008", "Wait/event WFI/WFE/WFIT/WFET/SEV/SEVL", "ARMv8.0-A (WFxT selected)",
      "WFI/WFE/WFIT/WFET/SEV/SEVL", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py; sim/difftest/test_program.py",
      "QEMU 11.1.0 + fork idle/wfxt plugins strict lockstep",
      "wait 边界/超时模拟",
      "idle/wake async commit; timer sidecar",
      "单核事件; EL0 trap 完整语义后置"),
    R("BASE-SYS-009", "Data cache maintenance DC", "ARMv8.0-A",
      "DC ZVA/CVAC/CVAU/CIVAC/IVAC/CVAP (and ISW recognition)", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv; rtl/lcvex_l1_d.sv; rtl/lcvex_l2.sv",
      "tb/sv/lcvex_l1_d_tb.sv; tb/sv/lcvex_l2_tb.sv; tb/sv/lcvex_b3_maint_decode_tb.sv",
      "sim/cocotb/test_l1_d_wb.py; test_l2_wb.py",
      "QEMU 11.1.0 strict lockstep; hard_maint_v82*",
      "DC CVADP/EL2/EL3 后置; unknown op UDEF; EL0 DZE/UCI gate",
      "cache maintenance, commit; no new sidecar",
      "CVAP 无持久介质按无副作用; DC ZVA EL0 DZE gate"),
    R("BASE-SYS-010", "Instruction cache maintenance IC", "ARMv8.0-A",
      "IC IALLU/IVAU", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_l1_i.sv",
      "tb/sv/lcvex_l1_i_tb.sv",
      "sim/cocotb/test_l1_d_wb.py",
      "QEMU 11.1.0 strict lockstep; hard_selfmod",
      "其它 IC 操作后置/UDEF",
      "I-cache invalidate, commit",
      "配合 ISB 自修改代码"),
    R("BASE-SYS-011", "TLBI EL1 baseline", "ARMv8.0-A",
      "TLBI VMALLE1/VAE1/ASIDE1/VAAE1/VALE1/VAALE1 (IS & non-IS)", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_mmu.sv",
      "tb/sv/lcvex_mmu_tb.sv; tb/sv/lcvex_b3_maint_decode_tb.sv",
      "sim/cocotb/test_lcvex_core.py; sim/difftest/test_program.py",
      "QEMU 11.1.0 strict lockstep; hard_tlbi",
      "OS/RV/range 后置/UDEF; op1=4 EL2 space UDEF",
      "TLB invalidation, commit",
      "整表失效超集"),
    R("BASE-SYS-012", "Address translation AT + PAR_EL1", "ARMv8.0-A",
      "AT S1E1R/W/S1E0R/W/S1E1RP/WP", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_mmu.sv; rtl/lcvex_core.sv",
      "tb/sv/lcvex_mmu_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; hard_maint_v82_mmu",
      "AT S1E2/S1E3/EL2 后置 UDEF",
      "PAR_EL1 write, commit/checkpoint sidecar",
      "P 形式受 PAN 影响"),
    R("BASE-SYS-013", "Read-only ID/feature system registers", "ARMv8.0-A",
      "MIDR/REVIDR/ID_*/CTR/CLIDR/DCZID/CNTFRQ/MPIDR/OSLSR etc", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv; rtl/lcvex_pkg.sv",
      "tb/sv/lcvex_core_tb.sv; tb/sv/lcvex_b3_sysreg_access_tb.sv; sim/difftest/test_program.py",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 -cpu max probe; hard_id_sysreg",
      "未列 ID regs -> UDEF; OSLSR MSR UDEF",
      "read-only, commit/checkpoint sidecar",
      "QEMU 复位值回放; OSLSR=MRS 10"),
    R("BASE-SYS-014", "Read/write system registers for Linux", "ARMv8.0-A (profile-selected)",
      "CPACR/MDSCR/PMUSERENR/CNTKCTL/TPIDR/SP_EL0/TCR2/PIR/PIRE0/CSSELR/PAR/CONTEXTIDR/OSLAR etc", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv; rtl/lcvex_pkg.sv",
      "tb/sv/lcvex_core_tb.sv; tb/sv/lcvex_b3_sysreg_access_tb.sv; sim/difftest/test_program.py",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 sysreg probe / strict lockstep",
      "权限/掩码; unknown sysreg UDEF; OSLAR MRS UDEF",
      "sysreg state, commit/checkpoint sidecar",
      "含 PSTATE 别名寄存器; CONTEXTIDR reset 0"),
    R("BASE-SYS-015", "Generic timer", "ARMv8.0-A",
      "CNTPCT/CNTVCT/CNTP_*/CNTV_* (EL0/EL1, TVAL/CVAL/CTL)", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv; rtl/lcvex_pkg.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py; sim/difftest/test_program.py",
      "QEMU 11.1.0 -icount shift=0 + timer plugins strict lockstep",
      "EL0 gate/access trap EC=0x18; CNTVOFF_EL2=0",
      "timer state, checkpoint sidecar",
      "指令边界虚拟时间"),
    R("BASE-EXC-001", "Synchronous exception infrastructure", "ARMv8.0-A",
      "UDEF/SVC/IABT/DABT/PC-align/FP-access/sysreg-trap; ESR/FAR/ELR/SPSR/vector entry", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv; rtl/lcvex_pkg.sv",
      "tb/sv/lcvex_core_tb.sv; tb/sv/lcvex_mmu_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; run_p4b/run_p4c/run_gate_c",
      "保留/越权/越界负测全覆盖",
      "ELR/SPSR/ESR/FAR, exception commit",
      "EL0->EL1 / same-EL vector offsets"),
    R("BASE-EXC-002", "Asynchronous IRQ entry", "ARMv8.0-A (GICv2 platform)",
      "IRQ via GIC at normal commit boundary; DAIF/ALLINT intake", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv; rtl/lcvex_gic.sv",
      "tb/sv/lcvex_core_tb.sv; tb/sv/lcvex_soc_tb.sv",
      "sim/cocotb/test_lcvex_core.py; sim/cocotb/test_mmio_fabric.py",
      "QEMU 11.1.0 fork async exception protocol; hard_irq*",
      "FIQ 后置; MSR/ERET 后不抢占",
      "IRQ async commit, SPSR/ELR",
      "协议专用 exc_code=0x40"),
    R("BASE-EXC-003", "PSTATE save/restore", "ARMv8.0-A",
      "DAIF/SPSel/SSBS/UAO/PAN/DIT/TCO/ALLINT in SPSR_EL1 and checkpoint", True, "V82-BASE", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv; rtl/lcvex_pkg.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py; sim/difftest/test_program.py",
      "QEMU 11.1.0 strict lockstep; hard_dit/hard_allint",
      "SPSR 保留位边界",
      "PSTATE + SPSR/checkpoint sidecar",
      "含 FEAT_NMI ALLINT bit"),
    R("BASE-MMU-001", "VMSAv8-64 page table walk", "ARMv8.0-A",
      "L0-L3 4KB/2MB/1GB descriptors; T0SZ/T1SZ; PA range", True, "V82-BASE", "implemented",
      "rtl/lcvex_mmu.sv",
      "tb/sv/lcvex_mmu_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 ptw strict lockstep; hard_block_desc/hard_ttbr_gap",
      "无效/gap/PA OOB -> translation fault",
      "TLB + walk state, commit",
      "单级 64-entry TLB (RTL)"),
    R("BASE-MMU-002", "Data access permission matrix", "ARMv8.0-A",
      "AP[1:0] EL0/EL1 read/write; simple_ap_to_rw_prot", True, "V82-BASE", "implemented",
      "rtl/lcvex_mmu.sv",
      "tb/sv/lcvex_mmu_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 ptw; hard_ap_matrix",
      "AP=00/10 fault cases",
      "translation fault, commit",
      "与 QEMU 矩阵逐项一致"),
    R("BASE-MMU-003", "Access flag / AF", "ARMv8.0-A (HAFDBS not selected)",
      "AF=0 -> AccessFlag fault when TCR_EL1.HA=0", True, "V82-BASE", "implemented",
      "rtl/lcvex_mmu.sv",
      "tb/sv/lcvex_mmu_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 ptw; hard_af",
      "HA=1/TCR2 HAFDBS 后置",
      "translation fault, commit",
      "不填充 TLB"),
    R("BASE-MMU-004", "Instruction permission UXN/PXN/W^X", "ARMv8.0-A",
      "UXN/PXN and EL0-writable page W^X for EL1 fetch", True, "V82-BASE", "implemented",
      "rtl/lcvex_mmu.sv",
      "tb/sv/lcvex_mmu_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 get_S1prot; hard_uxn_pxn",
      "AP=01 EL1 fetch fault",
      "IABT, commit",
      "P/UXN 矩阵"),
    R("BASE-MMU-005", "TLB and TLBI invalidation", "ARMv8.0-A",
      "64-entry fully-assoc TLB; TLBI EL1 uniform whole-table", True, "V82-BASE", "implemented",
      "rtl/lcvex_mmu.sv; rtl/lcvex_decode.sv",
      "tb/sv/lcvex_mmu_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; hard_tlbi",
      "OS/RV/range 后置",
      "TLB invalidated, commit",
      "写 SCTLR/TCR/TTBR 自动失效后置"),
    R("BASE-MMU-006", "PAN", "ARMv8.0-A",
      "PSTATE.PAN=1 blocks EL0-accessible data pages in EL1", True, "V82-BASE", "implemented",
      "rtl/lcvex_mmu.sv; rtl/lcvex_core.sv",
      "tb/sv/lcvex_mmu_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; hard_maint_v82",
      "AT S1E1RP/WP with PAN",
      "permission fault, commit",
      "TLB hit and walk consistent"),
    R("BASE-MMU-007", "MAIR cache attributes and bypass", "ARMv8.0-A",
      "MAIR_EL1 attr; Device/NC/WB; L1D/L2 bypass", True, "V82-BASE", "implemented",
      "rtl/lcvex_mmu.sv; rtl/lcvex_l1_d.sv; rtl/lcvex_l2.sv; rtl/lcvex_mem.sv",
      "tb/sv/lcvex_l1_d_tb.sv; tb/sv/lcvex_l2_tb.sv",
      "sim/cocotb/test_l1_d_wb.py; test_l2_wb.py",
      "QEMU 11.1.0 strict lockstep; hard_mair_bypass",
      "未列 attr 组合",
      "cache/mem side effects",
      "顺序单核缓存模型"),
    R("BASE-CACHE-001", "L1 I-cache", "ARMv8.0-A",
      "I-L1 line fetch/invalidate; SRAM 1MiB initial", True, "V82-BASE", "implemented",
      "rtl/lcvex_l1_i.sv",
      "tb/sv/lcvex_l1_i_tb.sv",
      "sim/cocotb/test_l1_d_wb.py",
      "QEMU 11.1.0 strict lockstep; run_m2_4b",
      "cache ops and coherency boundary tests",
      "I-cache state",
      "P6 Linux boot path"),
    R("BASE-CACHE-002", "L1 D-cache and write-through/writeback", "ARMv8.0-A",
      "D-L1 line fill/write/clean/invalidate; DC ZVA/CVAC/CVAU/CIVAC", True, "V82-BASE", "implemented",
      "rtl/lcvex_l1_d.sv; rtl/lcvex_l1_d_wb.sv",
      "tb/sv/lcvex_l1_d_tb.sv; tb/sv/lcvex_l1_d_wb_tb.sv",
      "sim/cocotb/test_l1_d_wb.py",
      "QEMU 11.1.0 strict lockstep; cache TBs",
      "fault/backpressure/coherence tests",
      "cache + mem side effects",
      "write-through under early config"),
    R("BASE-CACHE-003", "Unified L2 cache and memory interface", "ARMv8.0-A",
      "L2 line allocation, read/write, writeback, flush; AXI4 downstream", True, "V82-BASE", "implemented",
      "rtl/lcvex_l2.sv; rtl/lcvex_l2_wb.sv; rtl/lcvex_axi4_master.sv; rtl/lcvex_mem_arb.sv",
      "tb/sv/lcvex_l2_tb.sv; tb/sv/lcvex_l2_wb_tb.sv; tb/sv/lcvex_axi4_tb.sv",
      "sim/cocotb/test_l2_wb.py; sim/cocotb/test_axi4.py",
      "QEMU 11.1.0 strict lockstep + cache probes",
      "multi-core/coherence deferred; L2 probe contract",
      "memory side effects, checkpoint",
      "单核 release train"),
    R("BASE-PLAT-001", "PL011 UART MMIO", "ARMv8.0-A platform (QEMU virt)",
      "PL011 register subset at 0x09000000", True, "V82-BASE", "implemented",
      "rtl/lcvex_pl011.sv",
      "tb/sv/lcvex_pl011_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 hw/char/pl011.c strict lockstep; hard_uart",
      "unsupported registers/access UDEF/default",
      "MMIO state",
      "Linux earlycon/serial"),
    R("BASE-PLAT-002", "PL061 GPIO MMIO", "ARMv8.0-A platform (QEMU virt)",
      "PL061 GPIO register subset at 0x09030000", True, "V82-BASE", "implemented",
      "rtl/lcvex_pl061.sv",
      "tb/sv/lcvex_pl061_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 hw/gpio/pl061.c; hard_pl061",
      "unknown registers",
      "GPIO state",
      "P6 deterministic simulation"),
    R("BASE-PLAT-003", "PL031 RTC via C++ MMIO fabric", "ARMv8.0-A platform (QEMU virt)",
      "PL031 register subset at 0x09010000; C++ model", True, "V82-BASE", "implemented",
      "rtl/lcvex_mmio_fabric.sv; sim/mmio/lcvex_mmio_fabric.cc",
      "tb/sv/lcvex_mmio_fabric_tb.sv",
      "sim/cocotb/test_mmio_fabric.py",
      "QEMU 11.1.0 -rtc base ... clock=vm; hard_pl031",
      "unknown MMIO faults",
      "dev.mmio checkpoint sidecar",
      "C++ model shared with diff"),
    R("BASE-PLAT-004", "GICv2/GICv2m interrupt controller", "ARMv8.0-A platform (QEMU virt)",
      "GICD/GICC/GICv2m register subset; single core", True, "V82-BASE", "implemented",
      "rtl/lcvex_gic.sv",
      "tb/sv/lcvex_soc_tb.sv",
      "sim/cocotb/test_lcvex_core.py; test_mmio_fabric.py",
      "QEMU 11.1.0 hw/intc/arm_gic*.c; hard_gic/hard_irq",
      "FIQ/multi-core SPIs deferred",
      "GIC state/checkpoint sidecar",
      "单核无安全扩展"),

    # ========== V82-SELECTED-EXT ==========
    R("EXT-FP-000", "FP/AdvSIMD architectural state and FPEN", "ARMv8.0-A (selected FP/ASIMD)",
      "V0-V31, FPCR/FPSR, CPACR_EL1.FPEN, FP access trap EC=0x07", True, "V82-SELECTED-EXT", "implemented",
      "rtl/lcvex_fp_state.sv; rtl/lcvex_decode.sv; rtl/lcvex_core.sv",
      "tb/sv/lcvex_fp_state_tb.sv",
      "sim/cocotb/test_fp_state.py; sim/cocotb/test_p7_fp_scalar.py",
      "QEMU 11.1.0 Cortex-A76 required FP/NEON wire + checkpoint sidecar",
      "FPEN denied -> EXC_FP_ACCESS, no effect; reserved FPCR/FPSR RAZ/WI",
      "V/FPCR/FPSR/CPACR + LCVXFP01 checkpoint",
      "P7-0"),
    R("EXT-FP-001", "Scalar FP move", "ARMv8.0-A FP32/64 + FP16 (selected)",
      "FMOV (reg/imm) S/D/H", True, "V82-SELECTED-EXT", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_fp_scalar.sv",
      "tb/sv/lcvex_fp_scalar_tb.sv; tb/sv/lcvex_fp_scalar_p7_5_tb.sv",
      "sim/cocotb/test_p7_fp_scalar.py; sim/cocotb/test_p7_5_fp16_sqrt_minmax_round.py",
      "QEMU 11.1.0 Cortex-A76 required strict lockstep",
      "reserved/FP16-unsupported forms UDEF",
      "V write, FP checkpoint",
      "P7-1/P7-5"),
    R("EXT-FP-002", "Scalar FP add/sub/mul/div", "ARMv8.0-A FP32/64 + FP16 (selected)",
      "FADD/FSUB/FMUL/FDIV S/D/H", True, "V82-SELECTED-EXT", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_fp_scalar.sv",
      "tb/sv/lcvex_fp_scalar_tb.sv; tb/sv/lcvex_fp_scalar_p7_5_tb.sv",
      "sim/cocotb/test_p7_fp_scalar.py; sim/cocotb/test_p7_5_fp16_sqrt_minmax_round.py",
      "QEMU 11.1.0 Cortex-A76 required strict lockstep; raw-bit matrices",
      "FP16 reserved type / unsupported op UDEF",
      "V/FPSR, FP checkpoint",
      "P7-1 + P7-5 FP16"),
    R("EXT-FP-003", "Scalar FP compare", "ARMv8.0-A FP32/64 + FP16 (selected)",
      "FCMP reg/#0 S/D/H; FCMPE stays UDEF", True, "V82-SELECTED-EXT", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_fp_scalar.sv",
      "tb/sv/lcvex_fp_scalar_tb.sv",
      "sim/cocotb/test_p7_fp_scalar.py",
      "QEMU 11.1.0 Cortex-A76 required strict lockstep",
      "FCMPE UDEF; ordered compare not selected",
      "NZCV + FPSR, FP checkpoint",
      "quiet compare only"),
    R("EXT-FP-004", "Scalar FP sqrt", "ARMv8.0-A FP32/64 + FP16 (selected)",
      "FSQRT S/D/H", True, "V82-SELECTED-EXT", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_fp_scalar.sv",
      "tb/sv/lcvex_fp_scalar_p7_5_tb.sv",
      "sim/cocotb/test_p7_5_fp16_sqrt_minmax_round.py",
      "QEMU 11.1.0 Cortex-A76 required; edge/rounding sequences",
      "negative/NaN -> default NaN semantics",
      "V/FPSR, FP checkpoint",
      "P7-5"),
    R("EXT-FP-005", "Scalar FP min/max", "ARMv8.0-A FP32/64 + FP16 (selected)",
      "FMIN/FMAX/FMINNM/FMAXNM S/D/H", True, "V82-SELECTED-EXT", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_fp_scalar.sv",
      "tb/sv/lcvex_fp_scalar_p7_5_tb.sv",
      "sim/cocotb/test_p7_5_fp16_sqrt_minmax_round.py",
      "QEMU 11.1.0 Cortex-A76 required; NaN/signed-zero raw",
      "FMINNM/FMAXNM single QNaN behavior",
      "V/FPSR, FP checkpoint",
      "P7-5"),
    R("EXT-FP-006", "Scalar FP round to integral", "ARMv8.0-A FP32/64 + FP16 (selected)",
      "FRINTN/P/M/Z/A/I/X S/D/H", True, "V82-SELECTED-EXT", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_fp_scalar.sv",
      "tb/sv/lcvex_fp_scalar_p7_5_tb.sv",
      "sim/cocotb/test_p7_5_fp16_sqrt_minmax_round.py",
      "QEMU 11.1.0 Cortex-A76 required",
      "FRINTI uses FPCR.RMode vs FRINTX flags",
      "V/FPSR, FP checkpoint",
      "P7-5"),
    R("EXT-FP-007", "Scalar fused multiply-add", "ARMv8.0-A FP32/64/16 (selected)",
      "FMADD/FMSUB/FNMADD/FNMSUB S/D/H", True, "V82-SELECTED-EXT", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_fp_scalar.sv",
      "tb/sv/lcvex_fp_scalar_p7_4_tb.sv; tb/sv/lcvex_fp_scalar_p7_5_tb.sv",
      "sim/cocotb/test_p7_4_fma_convert.py; sim/cocotb/test_p7_5_fp16_sqrt_minmax_round.py",
      "QEMU 11.1.0 Cortex-A76 required; NaN propagation",
      "esz=10 UDEF; by-element/vector H not covered by scalar row",
      "V/FPSR, FP checkpoint",
      "P7-4/B2a"),
    R("EXT-FP-008", "Scalar int/fixed -> FP convert", "ARMv8.0-A FP32/64 (selected)",
      "SCVTF/UCVTF W/X -> S/D (integer and fixed-point)", True, "V82-SELECTED-EXT", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_fp_scalar.sv",
      "tb/sv/lcvex_fp_scalar_p7_4_tb.sv",
      "sim/cocotb/test_p7_4_fma_convert.py",
      "QEMU 11.1.0 Cortex-A76 required",
      "FP16/vector fixed offset not selected UDEF",
      "V/FPSR, FP checkpoint",
      "P7-4"),
    R("EXT-FP-009", "Scalar FP -> int/fixed convert", "ARMv8.0-A FP32/64 (selected)",
      "FCVTZS/FCVTZU S/D -> W/X (integer and fixed-point)", True, "V82-SELECTED-EXT", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_fp_scalar.sv",
      "tb/sv/lcvex_fp_scalar_p7_4_tb.sv",
      "sim/cocotb/test_p7_4_fma_convert.py",
      "QEMU 11.1.0 Cortex-A76 required",
      "FP16 conversion/vector fixed UDEF",
      "GPR + FPSR, FP checkpoint",
      "P7-4"),
    R("EXT-FP-010", "Scalar/vector FP format convert FCVT", "ARMv8.0-A FP16/FP32/FP64 (selected)",
      "FCVT S<->D, H<->S, H<->D", True, "V82-SELECTED-EXT", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_fp_scalar.sv",
      "tb/sv/lcvex_fp_scalar_p7_4_tb.sv; tb/sv/lcvex_fp_scalar_p7_5_tb.sv",
      "sim/cocotb/test_p7_4_fma_convert.py; sim/cocotb/test_p7_5_fp16_sqrt_minmax_round.py",
      "QEMU 11.1.0 Cortex-A76 required; edge NaN payload",
      "vector FCVT and other conversions UDEF",
      "V/FPSR, FP checkpoint",
      "P7-4/P7-5"),
    R("EXT-FP-011", "Scalar FP memory LDR/STR S/D", "ARMv8.0-A FP (selected)",
      "LDR/STR S/D unsigned-offset", True, "V82-SELECTED-EXT", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv; rtl/lcvex_fp_state.sv",
      "tb/sv/lcvex_fp_scalar_tb.sv",
      "sim/cocotb/test_p7_fp_scalar.py",
      "QEMU 11.1.0 Cortex-A76 required; load fault no V effect",
      "LDR/STR H not implemented -> blocked (see EXT-FP-012)",
      "mem + V, FP checkpoint",
      "P7-1"),
    R("EXT-FP-012", "Scalar FP16 memory LDR/STR H", "ARMv8.2-A FP16 (selected but gap)",
      "LDR/STR H scalar", True, "V82-SELECTED-EXT", "blocked",
      "rtl/lcvex_decode.sv (not wired)",
      "none",
      "none",
      "QEMU 11.1.0 Cortex-A76 supports; RTL lacks scalar H load/store",
      "not yet covered",
      "would add V/mem effect",
      "P7-5 明确不实现；待 B2 决策"),
    R("EXT-NEON-001", "NEON move/MOVI", "ARMv8.0-A ASIMD (selected)",
      "MOVI Vd.16B/.8H/.4S; ORR Vd.16B (MOV alias)", True, "V82-SELECTED-EXT", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_neon_int.sv",
      "tb/sv/lcvex_neon_int_tb.sv",
      "sim/cocotb/test_p7_2_neon.py",
      "QEMU 11.1.0 Cortex-A76 required; A76 lockstep 31",
      "unsupported cmode/lane UDEF",
      "V write, FP checkpoint",
      "P7-2"),
    R("EXT-NEON-002", "NEON bitwise", "ARMv8.0-A ASIMD (selected)",
      "AND/ORR/EOR/BIC/ORN Vd.16B", True, "V82-SELECTED-EXT", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_neon_int.sv",
      "tb/sv/lcvex_neon_int_tb.sv",
      "sim/cocotb/test_p7_2_neon.py",
      "QEMU 11.1.0 Cortex-A76 required",
      "lane-size variants not selected UDEF",
      "V write, FP checkpoint",
      "P7-2"),
    R("EXT-NEON-003", "NEON integer add/sub", "ARMv8.0-A ASIMD (selected)",
      "ADD/SUB Vd.<16B/8H/4S/2D>", True, "V82-SELECTED-EXT", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_neon_int.sv",
      "tb/sv/lcvex_neon_int_tb.sv",
      "sim/cocotb/test_p7_2_neon.py",
      "QEMU 11.1.0 Cortex-A76 required",
      "saturating/narrow not selected UDEF",
      "V write, FP checkpoint",
      "P7-2"),
    R("EXT-NEON-004", "NEON integer compare", "ARMv8.0-A ASIMD (selected)",
      "CMEQ/CMGE/CMGT/CMHI/CMHS Vd.<T>", True, "V82-SELECTED-EXT", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_neon_int.sv",
      "tb/sv/lcvex_neon_int_tb.sv",
      "sim/cocotb/test_p7_2_neon.py",
      "QEMU 11.1.0 Cortex-A76 required",
      "FCMEQ separate; other FP compares UDEF",
      "V write, FP checkpoint",
      "P7-2/P7-3"),
    R("EXT-NEON-005", "NEON integer shifts", "ARMv8.0-A ASIMD (selected)",
      "SHL/SSHR/USHR/SSRA/USRA Vd.<T>,#imm", True, "V82-SELECTED-EXT", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_neon_int.sv",
      "tb/sv/lcvex_neon_int_tb.sv",
      "sim/cocotb/test_p7_2_neon.py",
      "QEMU 11.1.0 Cortex-A76 required",
      "illegal immh UDEF; variable shift not selected",
      "V write, FP checkpoint",
      "P7-2"),
    R("EXT-NEON-006", "NEON single Q load/store", "ARMv8.0-A ASIMD (selected)",
      "LDR Qd/STR Qd [Xn,#imm] (16B natural aligned)", True, "V82-SELECTED-EXT", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv; rtl/lcvex_fp_state.sv",
      "tb/sv/lcvex_neon_int_tb.sv; tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_p7_2_neon.py",
      "QEMU 11.1.0 Cortex-A76 required; two 8B memory segments",
      "misaligned/fault precheck; structured/lane/pair UDEF",
      "V + mem, FP checkpoint",
      "P7-2"),
    R("EXT-NEON-FP-001", "NEON FP arithmetic and compare", "ARMv8.0-A ASIMD FP (selected)",
      "FADD/FSUB/FMUL/FCMEQ 2S/4S/2D; 4H/8H FADD/FSUB/FMUL/FCMEQ", True, "V82-SELECTED-EXT", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_neon_fp.sv",
      "tb/sv/lcvex_neon_fp_tb.sv; tb/sv/lcvex_neon_fp_p7_4_tb.sv; tb/sv/lcvex_neon_fp_p7_5_tb.sv",
      "sim/cocotb/test_p7_3_neon_fp.py; sim/cocotb/test_p7_5_fp16_sqrt_minmax_round.py",
      "QEMU 11.1.0 Cortex-A76 required; 48/102 etc",
      "FCMGE/FCMGT/FP16 FMA UDEF",
      "V/FPSR, FP checkpoint",
      "P7-3/P7-5"),
    R("EXT-NEON-FP-002", "NEON vector FMA", "ARMv8.0-A ASIMD FP (selected)",
      "FMLA/FMLS 2S/4S/2D/4H/8H", True, "V82-SELECTED-EXT", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_neon_fp.sv",
      "tb/sv/lcvex_neon_fp_p7_4_tb.sv; tb/sv/lcvex_neon_fp_p7_5_tb.sv",
      "sim/cocotb/test_p7_4_fma_convert.py; sim/cocotb/test_p7_5_fp16_sqrt_minmax_round.py",
      "QEMU 11.1.0 Cortex-A76 required",
      "by-element FMA UDEF",
      "V/FPSR, FP checkpoint",
      "P7-4/B2a"),
    R("EXT-NEON-FP-003", "NEON vector int/fixed convert", "ARMv8.0-A ASIMD FP (selected)",
      "SCVTF/UCVTF/FCVTZS/FCVTZU 2S/4S/2D (integer forms)", True, "V82-SELECTED-EXT", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_neon_fp.sv",
      "tb/sv/lcvex_neon_fp_p7_4_tb.sv",
      "sim/cocotb/test_p7_4_fma_convert.py",
      "QEMU 11.1.0 Cortex-A76 required",
      "fixed-point vector/FP16 conversion UDEF",
      "V/FPSR, FP checkpoint",
      "P7-4"),
    R("EXT-NEON-FP-004", "NEON vector sqrt/min/max/rint", "ARMv8.0-A ASIMD FP (selected)",
      "FSQRT/FMIN/FMAX/FMINNM/FMAXNM/FRINT* 2S/4S/2D", True, "V82-SELECTED-EXT", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_neon_fp.sv",
      "tb/sv/lcvex_neon_fp_p7_5_tb.sv",
      "sim/cocotb/test_p7_5_fp16_sqrt_minmax_round.py",
      "QEMU 11.1.0 Cortex-A76 required",
      "4H/8H min/max/sqrt/rint not selected UDEF",
      "V/FPSR, FP checkpoint",
      "P7-5"),
    R("EXT-CRC-001", "CRC32/CRC32C", "ARMv8.0-A CRC extension (selected)",
      "CRC32/CRC32C B/H/W/X", True, "V82-SELECTED-EXT", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_alu.sv",
      "tb/sv/lcvex_crc_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; hard_crc32",
      "reserved sizes UDEF",
      "GPR, ordinary commit",
      "IEEE and Castagnoli reflected"),
    R("EXT-LSE-001", "LSE single-register atomic", "ARMv8.1-A LSE (selected)",
      "LDADD/LDCLR/LDEOR/LDSET/LDSMAX/LDSMIN/LDUMAX/LDUMIN/SWP B/H/W/X; ST* aliases", True, "V82-SELECTED-EXT", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv; rtl/lcvex_mem.sv",
      "tb/sv/lcvex_core_tb.sv; tb/sv/lcvex_b3_atomic_barrier_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; hard_lse_atomic",
      "illegal Rt=31 etc; reserve op UDEF",
      "GPR + mem, commit",
      "读旧值→计算→写回; B/H/W/X + acq/rel matrix"),
    R("EXT-LSE-002", "LSE CAS variants", "ARMv8.1-A LSE (selected)",
      "CAS/CASA/CASL/CASAL W/X", True, "V82-SELECTED-EXT", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv; rtl/lcvex_mem.sv",
      "tb/sv/lcvex_core_tb.sv; tb/sv/lcvex_b3_atomic_barrier_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; hard_lse_atomic",
      "CASP etc separately; reserved op UDEF",
      "GPR + mem, commit",
      "条件写回; B/H/W/X + CASAL matrix"),
    R("EXT-LSE128-001", "LSE128 CASP family", "ARMv8.1-A LSE128 (selected subset)",
      "CASP/CASPA/CASPL/CASPAL X pair", True, "V82-SELECTED-EXT", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv; rtl/lcvex_mem.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; hard_casp/lse128",
      "alignment/range/MEM fault precheck; illegal rt2 UDEF",
      "2xGPR + 2x8B mem, commit",
      "单核四阶段事务"),
    R("EXT-LSE128-002", "LSE128 LDCLRP/LDSETP/SWPP", "ARMv8.1-A LSE128 (selected subset)",
      "LDCLRP/LDSETP/SWPP X pair", True, "V82-SELECTED-EXT", "implemented",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv; rtl/lcvex_mem.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 strict lockstep; hard_lse128",
      "alignment/range/MMU cross-page precheck",
      "2xGPR + 2x8B mem, commit",
      "单核事务；其它 LSE128 多核后置"),

    # ========== V82-SVE-EXCLUDED ==========
    R("SVE-001", "SVE vector architectural state", "ARMv8.2-A SVE (excluded)",
      "Z0-Z31/P0-P15/FFR, variable VL, vectored state", False, "V82-SVE-EXCLUDED", "deferred",
      "not implemented (P8 roadmap)",
      "none",
      "none",
      "QEMU 11.1.0 -cpu max SVE exists; RTL has no vector state",
      "SVE instructions currently UDEF/not decoded; ZCR/RDVL shim only",
      "would need new checkpoint sidecar (not present)",
      "明确排除，不计入本轮完成度"),
    R("SVE-002", "SVE integer/FP/memory instruction families", "ARMv8.2-A SVE (excluded)",
      "SVE load/store, predicate, arithmetic, reductions, gathers/scatters", False, "V82-SVE-EXCLUDED", "deferred",
      "not implemented",
      "none",
      "none",
      "QEMU 11.1.0 -cpu max supports; not in RTL/profile",
      "UDEF / no decode",
      "would require P8 vector pipeline/checkpoint",
      "明确排除"),
    R("SVE-003", "SVE2", "ARMv8.5-A SVE2 (excluded)",
      "All SVE2 instruction families", False, "V82-SVE-EXCLUDED", "deferred",
      "not implemented",
      "none",
      "none",
      "QEMU 11.1.0 -cpu max supports; not in RTL/profile",
      "UDEF / no decode",
      "P8+ only",
      "不在 V82 profile"),
    R("SVE-004", "SME/ZA state and instructions", "ARMv8.2-A SME (excluded)",
      "ZA/Z tiles, SME instructions, streaming mode", False, "V82-SVE-EXCLUDED", "deferred",
      "not implemented",
      "none",
      "none",
      "QEMU 11.1.0 -cpu max SME exists; RTL lacks state",
      "SMCR/RDSVL etc are shims only",
      "would require SME checkpoint",
      "明确排除"),
    R("SVE-005", "SVE/SME probe shim ZCR/RDVL/SMCR/RDSVL", "ARMv8.2-A SVE/SME (excluded, probe-compatible)",
      "ZCR_EL1, RDVL, SMCR_EL1, RDSVL, SMPRI_EL1, SMIDR_EL1, TPIDR2_EL0", False, "V82-SVE-EXCLUDED", "shim",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv; rtl/lcvex_pkg.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 -cpu max lockstep; hard_sve_probe",
      "only scalar VL calculation, no vector state",
      "ZCR/SMCR in checkpoint sidecar v2/v3",
      "不是 SVE 实现，仅为 Linux 探测兼容"),

    # ========== POST-V82-DEFERRED ==========
    R("DEF-PAUTH-001", "Pointer authentication PAuth", "ARMv8.3-A (deferred)",
      "PACIA/PACIB/PACDA/PACDB/PACGA, AUTIA/AUTIB, PACIASP/AUTIASP; key regs", False, "POST-V82-DEFERRED", "shim",
      "rtl/lcvex_decode.sv (hint/RAZ paths)",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 -cpu max pauth available; current RTL aligns QEMU pauth=off/NOP",
      "PACIASP etc as NOP; key regs RAZ/WI",
      "no PAuth key checkpoint",
      "未获本轮批准"),
    R("DEF-BTI-001", "Branch target identification BTI", "ARMv8.5-A (deferred)",
      "BTI hint encodings; SCTLR_EL1.BT", False, "POST-V82-DEFERRED", "shim",
      "rtl/lcvex_decode.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 SCTLR.BT=0 default; hints NOP",
      "BTI c/j/jc treated as NOP",
      "no architectural effect",
      "非本轮批准扩展"),
    R("DEF-RCPC-001", "RCpc load-acquire PC-rel", "ARMv8.3-A (deferred)",
      "LDAPR/LDAPUR (B/H/W/X)", False, "POST-V82-DEFERRED", "deferred",
      "not implemented",
      "none",
      "none",
      "QEMU 11.1.0 supports; RTL does not decode as LDAPR",
      "ldar/stlr only; reserved/UDEF",
      "would need acquire semantics/mem commit",
      "明确后置"),
    R("DEF-MTE-001", "Memory tagging MTE", "ARMv8.5-A (deferred)",
      "ADDG/SUBG, LDG/STG/STZG, tag sysregs, TCO", False, "POST-V82-DEFERRED", "deferred",
      "not implemented (ADDG/SUBG UDEF; TCO PSTATE only)",
      "none",
      "none",
      "QEMU 11.1.0 supports; not in RTL/profile",
      "ADDG/SUBG bit23=1 UDEF",
      "would require tag state/checkpoint",
      "明确后置"),
    R("DEF-MOPS-001", "Memory copy/set MOPS", "ARMv8.6-A (deferred)",
      "CPY/CPYM/CPYE, SETP/SETM/SETE", False, "POST-V82-DEFERRED", "deferred",
      "not implemented",
      "none",
      "none",
      "QEMU 11.1.0 supports; not in RTL",
      "UDEF",
      "would require multi-instruction mem effects",
      "明确后置"),
    R("DEF-LSE128-001", "Other LSE128 families and multi-core consistency", "ARMv8.1-A+ (deferred)",
      "Other 128-bit atomic operations; multi-core atomic ordering", False, "POST-V82-DEFERRED", "deferred",
      "not implemented beyond selected CASP/LDCLRP/LDSETP/SWPP",
      "none",
      "none",
      "QEMU 11.1.0 supports more LSE128; RTL subset only",
      "unknown/other encodings UDEF",
      "would require multi-core memory model",
      "C 线/后续 profile"),
    R("DEF-CRYPTO-001", "Crypto/AES/SHA/PMULL", "ARMv8.0-A optional crypto (deferred)",
      "AES, SHA1/SHA2, PMULL, CRC? (CRC selected separately)", False, "POST-V82-DEFERRED", "deferred",
      "not implemented",
      "none",
      "none",
      "QEMU 11.1.0 -cpu max supports; not in RTL",
      "UDEF",
      "would add vector crypto state/effects",
      "未获本轮批准"),
    R("DEF-RAS-001", "RAS extension registers", "ARMv8.2-A RAS (deferred/shim)",
      "ISR_EL1, DISR_EL1", False, "POST-V82-DEFERRED", "shim",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 probe; RAZ/WI",
      "RAS ERROR/record not implemented",
      "no state",
      "shim, not counted"),
    R("DEF-DEBUG-001", "External debug/PMU", "ARMv9/optional (deferred)",
      "DBGBVR/BCR/WVR/WCR, OSDLR/OSLAR, PMU event counters", False, "POST-V82-DEFERRED", "shim",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 debug regs; P6 RAZ/WI/dummy",
      "debug monitor closed; PMU unimplemented",
      "no debug state",
      "P9 后置"),
    R("DEF-EL2-001", "EL2/EL3 virtualization and security state", "ARMv8.2-A EL2/EL3 (deferred)",
      "SCTLR_EL2/HCR_EL2/VBAR_EL2/ELR_EL2/SPSR_EL2 etc; EL3", False, "POST-V82-DEFERRED", "shim",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv; rtl/lcvex_pkg.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 -cpu max has_el2/el3 false locks; read 0 write ignore",
      "EL2 access not architecturally trapped due to disabled EL2",
      "no EL2 state",
      "shim, not counted"),
    R("DEF-ECV-001", "FEAT_ECV self-synchronizing timer views", "ARMv8.6-A (deferred/shim)",
      "CNTPCTSS_EL0/CNTVCTSS_EL0", False, "POST-V82-DEFERRED", "shim",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 same-value view; strict lockstep",
      "FEAT_ECV trap/enable not implemented",
      "timer sidecar",
      "仅在 QEMU virt 路径兼容"),
    R("DEF-PIE-001", "FEAT_PIE/TCR2/PIR/PIRE0", "ARMv8.7-A? (deferred/shim)",
      "TCR2_EL1/PIR_EL1/PIRE0_EL1/SCTLR2_EL1", False, "POST-V82-DEFERRED", "shim",
      "rtl/lcvex_decode.sv; rtl/lcvex_core.sv; rtl/lcvex_pkg.sv",
      "tb/sv/lcvex_core_tb.sv",
      "sim/cocotb/test_lcvex_core.py",
      "QEMU 11.1.0 sysreg probe; mask/reset",
      "PIE not used for actual permission",
      "sysreg checkpoint",
      "Linux probe shim"),
    R("DEF-FPEXC-001", "FP exception enable/trap and full IEEE exception handling", "ARMv8.2-A FP (deferred)",
      "FPCR exception enable bits, FP exception traps", False, "POST-V82-DEFERRED", "deferred",
      "not implemented (FPCR exception enable RAZ/WI)",
      "tb/sv/lcvex_fp_state_tb.sv (negative)",
      "sim/cocotb/test_fp_state.py",
      "QEMU 11.1.0 A76 has limited trap handling; protocol declares not implemented",
      "FPCR IOE/DZE/OFE/UFE/IXE/IDE RAZ/WI",
      "would need FP exception commit/trap",
      "P7 明确延后"),
    R("DEF-FP-REMAIN-001", "Remaining FP/Advanced SIMD families", "ARMv8.0-A/8.2 optional (deferred)",
      "Non-selected FP/NEON: saturating, narrow, widen, permute, table, across-lane, structured/lane/replicate/pair memory, estimate, etc", False, "POST-V82-DEFERRED", "deferred",
      "not implemented",
      "none",
      "none",
      "QEMU 11.1.0 -cpu max supports; not in selected profile",
      "UDEF",
      "would expand V/mem checkpoint",
      "不是本轮 B 线范围"),
    R("DEF-MAINT-001", "Remaining cache/TLB maintenance", "ARMv8.0-A/8.2 optional (deferred)",
      "TLBI OS/RV/range, DC CVADP, EL2/EL3 maintenance, full cache coherence", False, "POST-V82-DEFERRED", "deferred",
      "not implemented",
      "none",
      "none",
      "QEMU 11.1.0 supports; RTL baseline subset only",
      "UDEF",
      "would extend cache/MMU checkpoint",
      "多核/平台后置"),
    R("DEF-PMU-001", "PMU event counting", "ARMv8.0-A optional (deferred)",
      "PMEVTYPER/PMEVCNTR/PMCCNTR etc", False, "POST-V82-DEFERRED", "deferred",
      "not implemented",
      "none",
      "none",
      "QEMU 11.1.0 supports; RTL PMUSERENR only",
      "PMU access UDEF/RAZ",
      "would add PMU sidecar",
      "P9 后置"),
]


# ---------------------------------------------------------------------------
# Manifest generation / validation
# ---------------------------------------------------------------------------

MANIFEST_META = {
    "schema_version": 1,
    "profile": "V82-non-SVE-audit",
    "title": "LCVEX V82 非 SVE Profile 机器可检查清单",
    "base_sha": "62192862bfb51fbc32cd0ee45ef1c1f5a0bde444",
    "branch": "feature/T-20260829-098-b5-profile-freeze",
    "worktree": "/home/chiro/projects/mycpu/lcvex-wt-T-20260829-088",
    "qemu": "QEMU 11.1.0 (local fork + patches; -cpu max/cortex-a76 strict lockstep)",
}


def validate_rows(rows):
    errors = []
    seen = set()
    for i, r in enumerate(rows):
        rid = r.get("row_id", f"<missing@{i}>")
        for field in sorted(REQUIRED_FIELDS):
            if field not in r:
                errors.append(f"{rid}: missing required field {field}")
        if r.get("category") not in CATEGORIES:
            errors.append(f"{rid}: invalid category {r.get('category')!r}")
        if r.get("status") not in STATUSES:
            errors.append(f"{rid}: invalid status {r.get('status')!r}")
        if r.get("required") not in (True, False):
            errors.append(f"{rid}: required must be boolean")
        if rid in seen:
            errors.append(f"{rid}: duplicate row_id")
        seen.add(rid)
        if not r.get("qemu_oracle", "").strip():
            errors.append(f"{rid}: qemu_oracle is empty; must have oracle or explicit blocked/deferred reason")
        if r.get("status") in ("blocked", "deferred") and not r.get("notes", "").strip():
            errors.append(f"{rid}: blocked/deferred row must have explicit notes/reason")
        if not r.get("encoding", "").strip():
            errors.append(f"{rid}: encoding is empty")
        if not r.get("arch_version", "").strip():
            errors.append(f"{rid}: arch_version is empty")
        if not r.get("rtl", "").strip():
            errors.append(f"{rid}: rtl location is empty")
    return errors


def summarize(rows):
    stats = {"total": len(rows)}
    for cat in sorted(CATEGORIES):
        stats[cat] = sum(1 for r in rows if r["category"] == cat)
    for st in sorted(STATUSES):
        stats[st] = sum(1 for r in rows if r["status"] == st)
    stats["implemented"] = sum(1 for r in rows if r["status"] == "implemented")
    stats["blocked_or_deferred"] = sum(
        1 for r in rows if r["status"] in ("blocked", "deferred"))
    return stats


def manifest_text(rows, meta):
    data = dict(meta)
    data["rows"] = rows
    text = [
        "# LCVEX V82 非 SVE Profile 机器可检查清单（B0 审计）",
        "",
        "> 任务 T-20260829-075 · 分支 `feature/T-20260829-075-b0-profile-audit` ·",
        "> 本文件由 `scripts/v82_profile_check.py --emit-manifest` 生成。",
        "> 机器可检查数据在下方 JSON 代码块，或直接以脚本内 ROWS 为准。",
        "",
        "## 口径（ADR-20260829-005）",
        "",
        "| Profile | 定义 | 本轮计数 |",
        "| --- | --- | --- |",
    ]
    stats = summarize(rows)
    for cat in sorted(CATEGORIES):
        text.append(f"| `{cat}` | 见 ADR | {stats[cat]} |")
    text += [
        "",
        "| 状态 | 说明 | 计数 |",
        "| --- | --- | --- |",
    ]
    for st in sorted(STATUSES):
        text.append(f"| `{st}` | 当前清单状态 | {stats[st]} |")
    text += [
        "",
        f"**总行数**: {stats['total']}；**implemented**: {stats['implemented']}；",
        f"**blocked/deferred**: {stats['blocked_or_deferred']}。",
        "",
        "## 分类 × 状态分布",
        "",
        "| 分类 | implemented | shim | udef | blocked | deferred |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    status_order = ["implemented", "shim", "udef", "blocked", "deferred"]
    for cat in sorted(CATEGORIES):
        row_cells = [cat]
        for st in status_order:
            row_cells.append(str(sum(1 for r in rows if r["category"] == cat and r["status"] == st)))
        text.append("| " + " | ".join(row_cells) + " |")
    text += [
        "",
        "## 缺口 / 后置清单（无 RTL 或明确未计入）",
        "",
        "| row_id | 分类 | 状态 | feature | 当前处置 |",
        "| --- | --- | --- | --- | --- |",
    ]
    for r in rows:
        if r["status"] in ("blocked", "deferred"):
            text.append(
                f"| `{r['row_id']}` | `{r['category']}` | `{r['status']}` | "
                f"{r['feature']} | {r['notes']} |"
            )
    text += [
        "",
        "## 分布与缺口摘要",
        "",
        "- V82-BASE 已实现标量/系统/异常/MMU/Cache 主体；logical shifted-register ROR 已实现，ADD/SUB shifted-register ROR 为保留 UDEF；V82-BASE 无 blocked 行。",
        "- V82-SELECTED-EXT 已登记 FP/ASIMD/FP16/CRC/LSE 选定子集；`LDR/STR H` 为 blocked。",
        "- V82-SVE-EXCLUDED 和 POST-V82-DEFERRED 不计入本轮完成度；SVE/SME 仅保留 probe shim。",
        "- 尚未有 RTL/oracle 的行已明确标为 blocked/deferred；不存在“已观察但未实现”的伪装支持。",
        "",
        "## 机器可检查数据",
        "",
        "<!-- V82_PROFILE_DATA_START -->",
        "```json",
        json.dumps(data, ensure_ascii=False, indent=2, sort_keys=True),
        "```",
        "<!-- V82_PROFILE_DATA_END -->",
        "",
        "## 校验方式",
        "",
        "```sh",
        "python3 scripts/v82_profile_check.py --validate-manifest",
        "python3 scripts/v82_profile_check.py --summary",
        "```",
    ]
    return "\n".join(text) + "\n"


def extract_manifest_json(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    m = re.search(r"<!-- V82_PROFILE_DATA_START -->\s*```json\s*(.*?)\s*```\s*<!-- V82_PROFILE_DATA_END -->",
                  text, re.S)
    if not m:
        raise SystemExit(f"{path}: cannot find embedded JSON block")
    return json.loads(m.group(1))


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--validate-manifest", action="store_true",
                    help="validate embedded JSON in docs/V82_PROFILE_MANIFEST.md")
    ap.add_argument("--emit-manifest", type=Path, default=None,
                    help="write/generate docs/V82_PROFILE_MANIFEST.md")
    ap.add_argument("--summary", action="store_true", help="print distribution")
    args = ap.parse_args(argv)

    if args.emit_manifest is not None:
        out = args.emit_manifest
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(manifest_text(ROWS, MANIFEST_META), encoding="utf-8")
        print(f"manifest written: {out}")
        return 0

    rows = ROWS
    errors = validate_rows(rows)
    if errors:
        for e in errors:
            print(f"ERROR: {e}", file=sys.stderr)
        return 1

    if args.validate_manifest:
        path = DEFAULT_MANIFEST if args.emit_manifest is None else args.emit_manifest
        if not path.exists():
            print(f"ERROR: manifest not found: {path}", file=sys.stderr)
            return 2
        data = extract_manifest_json(path)
        mrows = data.get("rows", [])
        mem_errors = validate_rows(mrows)
        if mem_errors:
            for e in mem_errors:
                print(f"ERROR(manifest): {e}", file=sys.stderr)
            return 1
        if mrows != ROWS:
            print("ERROR: manifest embedded rows differ from built-in ROWS", file=sys.stderr)
            return 1
        print(f"OK: manifest rows validated ({len(mrows)} rows)")

    if args.summary:
        stats = summarize(rows)
        for k in sorted(stats):
            print(f"{k}: {stats[k]}")

    if not args.validate_manifest and not args.summary:
        print(f"OK: built-in ROWS validated ({len(rows)} rows)")
        if errors:
            return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
