// sfl_sys.v

// Generated using ACDS version 21.4 67

`timescale 1 ps / 1 ps
module sfl_sys (
		input  wire        clk_in_clk_clk,             //   clk_in_clk.clk
		input  wire        epcq_avl_csr_read,          // epcq_avl_csr.read
		output wire        epcq_avl_csr_waitrequest,   //             .waitrequest
		input  wire        epcq_avl_csr_write,         //             .write
		input  wire [2:0]  epcq_avl_csr_address,       //             .address
		input  wire [31:0] epcq_avl_csr_writedata,     //             .writedata
		output wire [31:0] epcq_avl_csr_readdata,      //             .readdata
		output wire        epcq_avl_csr_readdatavalid, //             .readdatavalid
		input  wire        epcq_avl_mem_write,         // epcq_avl_mem.write
		input  wire [6:0]  epcq_avl_mem_burstcount,    //             .burstcount
		output wire        epcq_avl_mem_waitrequest,   //             .waitrequest
		input  wire        epcq_avl_mem_read,          //             .read
		input  wire [24:0] epcq_avl_mem_address,       //             .address
		input  wire [31:0] epcq_avl_mem_writedata,     //             .writedata
		output wire [31:0] epcq_avl_mem_readdata,      //             .readdata
		output wire        epcq_avl_mem_readdatavalid, //             .readdatavalid
		input  wire [3:0]  epcq_avl_mem_byteenable,    //             .byteenable
		input  wire        rst_in_reset_reset          // rst_in_reset.reset
	);

	wire    clk_out_clk_clk;     // clk:out_clk -> [epcq:clk, rst:clk]
	wire    rst_out_reset_reset; // rst:out_reset -> epcq:reset_n

	clk clk (
		.in_clk  (clk_in_clk_clk),  //   input,  width = 1,  in_clk.clk
		.out_clk (clk_out_clk_clk)  //  output,  width = 1, out_clk.clk
	);

	epcq epcq (
		.clk                  (clk_out_clk_clk),            //   input,   width = 1,       clock_sink.clk
		.reset_n              (~rst_out_reset_reset),       //   input,   width = 1,            reset.reset_n
		.avl_csr_read         (epcq_avl_csr_read),          //   input,   width = 1,          avl_csr.read
		.avl_csr_waitrequest  (epcq_avl_csr_waitrequest),   //  output,   width = 1,                 .waitrequest
		.avl_csr_write        (epcq_avl_csr_write),         //   input,   width = 1,                 .write
		.avl_csr_addr         (epcq_avl_csr_address),       //   input,   width = 3,                 .address
		.avl_csr_wrdata       (epcq_avl_csr_writedata),     //   input,  width = 32,                 .writedata
		.avl_csr_rddata       (epcq_avl_csr_readdata),      //  output,  width = 32,                 .readdata
		.avl_csr_rddata_valid (epcq_avl_csr_readdatavalid), //  output,   width = 1,                 .readdatavalid
		.avl_mem_write        (epcq_avl_mem_write),         //   input,   width = 1,          avl_mem.write
		.avl_mem_burstcount   (epcq_avl_mem_burstcount),    //   input,   width = 7,                 .burstcount
		.avl_mem_waitrequest  (epcq_avl_mem_waitrequest),   //  output,   width = 1,                 .waitrequest
		.avl_mem_read         (epcq_avl_mem_read),          //   input,   width = 1,                 .read
		.avl_mem_addr         (epcq_avl_mem_address),       //   input,  width = 25,                 .address
		.avl_mem_wrdata       (epcq_avl_mem_writedata),     //   input,  width = 32,                 .writedata
		.avl_mem_rddata       (epcq_avl_mem_readdata),      //  output,  width = 32,                 .readdata
		.avl_mem_rddata_valid (epcq_avl_mem_readdatavalid), //  output,   width = 1,                 .readdatavalid
		.avl_mem_byteenable   (epcq_avl_mem_byteenable),    //   input,   width = 4,                 .byteenable
		.irq                  ()                            //  output,   width = 1, interrupt_sender.irq
	);

	rst rst (
		.clk       (clk_out_clk_clk),     //   input,  width = 1,       clk.clk
		.in_reset  (rst_in_reset_reset),  //   input,  width = 1,  in_reset.reset
		.out_reset (rst_out_reset_reset)  //  output,  width = 1, out_reset.reset
	);

endmodule
